local addonName, addonTable = ...

-- Sound Database
local HMC_Sounds = {
    ["46_kilos"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\46_kilos.mp3",
    ["8_ev"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\8_ev.mp3",
    ["a_kurva_anyad_te_kocsog"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\a_kurva_anyad_te_kocsog.mp3",
    ["a_picsam_szebb"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\a_picsam_szebb.mp3",
    ["adj_egy_pofont"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\adj_egy_pofont.mp3",
    ["adott_mar_a_sors"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\adott_mar_a_sors.mp3",
    ["agyonvertel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\agyonvertel.mp3",
    ["ajtot_ablakot"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ajtot_ablakot.mp3",
    ["az_ital_nagy_szo"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\az_ital_nagy_szo.mp3",
    ["azt_mondta_a_lumper"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\azt_mondta_a_lumper.mp3",
    ["be_van_love"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\be_van_love.mp3",
    ["bekapcsolt_radio"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\bekapcsolt_radio.mp3",
    ["belovetted_magadat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\belovetted_magadat.mp3",
    ["bezarni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\bezarni.mp3",
    ["borsodi_vagyok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\borsodi_vagyok.mp3",
    ["boszorkany"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\boszorkany.mp3",
    ["boszorkany_kulonb"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\boszorkany_kulonb.mp3",
    ["budos_kocsog"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\budos_kocsog.mp3",
    ["buzsikam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\buzsikam.mp3",
    ["csakazenyem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\csakazenyem.mp3",
    ["drog_diller"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\drog_diller.mp3",
    ["dugulj_be"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\dugulj_be.mp3",
    ["egesz_gyerekemet"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\egesz_gyerekemet.mp3",
    ["egy_foga_van"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\egy_foga_van.mp3",
    ["egy_ket_pofont"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\egy_ket_pofont.mp3",
    ["egyedul_lejonni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\egyedul_lejonni.mp3",
    ["ehseg_betegseg"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ehseg_betegseg.mp3",
    ["elcsalni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\elcsalni.mp3",
    ["elmeletileg"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\elmeletileg.mp3",
    ["elnezest"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\elnezest.mp3",
    ["elsejovok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\elsejovok.mp3",
    ["elvette_tolem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\elvette_tolem.mp3",
    ["elvisz_engem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\elvisz_engem.mp3",
    ["ember_az_ember"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ember_az_ember.mp3",
    ["engedjetek_el"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\engedjetek_el.mp3",
    ["fasz_szopo"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\fasz_szopo.mp3",
    ["felcsinalni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\felcsinalni.mp3",
    ["feljelentem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\feljelentem.mp3",
    ["felmegyek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\felmegyek.mp3",
    ["felpofozom"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\felpofozom.mp3",
    ["fenyeget"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\fenyeget.mp3",
    ["figyelj_mar"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\figyelj_mar.mp3",
    ["fogfel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\fogfel.mp3",
    ["ha_ember_vagy"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ha_ember_vagy.mp3",
    ["had_mondja"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\had_mondja.mp3",
    ["hagyd_mar"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\hagyd_mar.mp3",
    ["hany_fogad_van"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\hany_fogad_van.mp3",
    ["harantfekvesben"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\harantfekvesben.mp3",
    ["hat_honapos"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\hat_honapos.mp3",
    ["hogynezelki"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\hogynezelki.mp3",
    ["ide_ulok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ide_ulok.mp3",
    ["idegileg"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\idegileg.mp3",
    ["ilyen_szokert"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ilyen_szokert.mp3",
    ["intenziv_korhazba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\intenziv_korhazba.mp3",
    ["isuzu"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\isuzu.mp3",
    ["kajakra_elvetted"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\kajakra_elvetted.mp3",
    ["ki_nevelni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ki_nevelni.mp3",
    ["kialla"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\kialla.mp3",
    ["kicsapongo"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\kicsapongo.mp3",
    ["kielegiteni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\kielegiteni.mp3",
    ["kinez_50nek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\kinez_50nek.mp3",
    ["kinyaltad"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\kinyaltad.mp3",
    ["kire_figyeljek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\kire_figyeljek.mp3",
    ["kopkod"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\kopkod.mp3",
    ["koporsoba_lakol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\koporsoba_lakol.mp3",
    ["le_fog_szoptatni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\le_fog_szoptatni.mp3",
    ["leall_inni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\leall_inni.mp3",
    ["lecsukatlak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\lecsukatlak.mp3",
    ["lehordol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\lehordol.mp3",
    ["lenyeg"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\lenyeg.mp3",
    ["leszoptatlak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\leszoptatlak.mp3",
    ["leszoptatom"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\leszoptatom.mp3",
    ["lopni_jarsz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\lopni_jarsz.mp3",
    ["lopol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\lopol.mp3",
    ["lopszcsalsz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\lopszcsalsz.mp3",
    ["lumper"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\lumper.mp3",
    ["maganyos_farkas"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\maganyos_farkas.mp3",
    ["majomvagyok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\majomvagyok.mp3",
    ["meg_fog_szoptatni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\meg_fog_szoptatni.mp3",
    ["megerdemelted"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\megerdemelted.mp3",
    ["megfogni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\megfogni.mp3",
    ["megfogom_a_szeket"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\megfogom_a_szeket.mp3",
    ["megkapta_a_csaladit"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\megkapta_a_csaladit.mp3",
    ["meglepetes"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\meglepetes.mp3",
    ["megoletel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\megoletel.mp3",
    ["mikor_ettel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\mikor_ettel.mp3",
    ["mikor_megismertem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\mikor_megismertem.mp3",
    ["mindent_ramfog"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\mindent_ramfog.mp3",
    ["mint_egy_kismalac"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\mint_egy_kismalac.mp3",
    ["mintegypitbull"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\mintegypitbull.mp3",
    ["mit_pofozol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\mit_pofozol.mp3",
    ["nafta"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nafta.mp3",
    ["ne_gyere"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ne_gyere.mp3",
    ["ne_szoljon_hozzam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ne_szoljon_hozzam.mp3",
    ["neked_nincs_olyan"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\neked_nincs_olyan.mp3",
    ["nem_allt_fel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nem_allt_fel.mp3",
    ["nem_borton_jar"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nem_borton_jar.mp3",
    ["nem_is_foglalkozok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nem_is_foglalkozok.mp3",
    ["nem_kapol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nem_kapol.mp3",
    ["nemkellesz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nemkellesz.mp3",
    ["nemrugol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nemrugol.mp3",
    ["nemvagysztar"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nemvagysztar.mp3",
    ["nezaklass"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nezaklass.mp3",
    ["nezaklasstelefonon"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nezaklasstelefonon.mp3",
    ["nincs_fogam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\nincs_fogam.mp3",
    ["oda_ra_irva"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\oda_ra_irva.mp3",
    ["olyan_lakasba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\olyan_lakasba.mp3",
    ["osszetapossa"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\osszetapossa.mp3",
    ["ot_gyermekem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ot_gyermekem.mp3",
    ["ozdonjatszd"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ozdonjatszd.mp3",
    ["ozdonmeno"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ozdonmeno.mp3",
    ["papir_ott_van"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\papir_ott_van.mp3",
    ["porolo_vassal"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\porolo_vassal.mp3",
    ["ramtett"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ramtett.mp3",
    ["rohadt_kocsog"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\rohadt_kocsog.mp3",
    ["sintervagy"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\sintervagy.mp3",
    ["sittesekkel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\sittesekkel.mp3",
    ["sms"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\sms.mp3",
    ["stilusait"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\stilusait.mp3",
    ["szegyen"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\szegyen.mp3",
    ["szepenbeszelj"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\szepenbeszelj.mp3",
    ["szeret_inni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\szeret_inni.mp3",
    ["sziv_repedes"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\sziv_repedes.mp3",
    ["szo_szot_kovet"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\szo_szot_kovet.mp3",
    ["szokincs"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\szokincs.mp3",
    ["sztarvagy"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\sztarvagy.mp3",
    ["tanulj_meg_olvasni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\tanulj_meg_olvasni.mp3",
    ["tele_ideggel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\tele_ideggel.mp3",
    ["tonkrement"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\tonkrement.mp3",
    ["tovabb"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\tovabb.mp3",
    ["tropara"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\tropara.mp3",
    ["tud_olvasni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\tud_olvasni.mp3",
    ["tudod_mi_az"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\tudod_mi_az.mp3",
    ["vadallat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\vadallat.mp3",
    ["valaszoljal"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\valaszoljal.mp3",
    ["vege_lehet"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\vege_lehet.mp3",
    ["ver_van"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\ver_van.mp3",
    ["vikkent_lakasokat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\vikkent_lakasokat.mp3",
    ["villany"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\villany.mp3",
    ["vissza_is_kapod"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\vissza_is_kapod.mp3",
    ["visszavontam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\visszavontam.mp3",
    ["zaklatol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Agi\\zaklatol.mp3",
    ["aki_eros"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Damu\\aki_eros.mp3",
    ["a_gecibe"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Damu\\a_gecibe.mp3",
    ["gyere_ide"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Damu\\gyere_ide.mp3",
    ["gyozo_nyert"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Damu\\gyozo_nyert.mp3",
    ["kinek_van_igaza"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Damu\\kinek_van_igaza.mp3",
    ["mit_szavazzak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Damu\\mit_szavazzak.mp3",
    ["nem_aludtam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Damu\\nem_aludtam.mp3",
    ["80szazalekig"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\80szazalekig.mp3",
    ["akilatta"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\akilatta.mp3",
    ["benedek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\benedek.mp3",
    ["ciganytelep"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\ciganytelep.mp3",
    ["cipobe"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\cipobe.mp3",
    ["drotozva"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\drotozva.mp3",
    ["ekkoranyaka"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\ekkoranyaka.mp3",
    ["elhiszem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\elhiszem.mp3",
    ["fantomkep"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\fantomkep.mp3",
    ["felmeres"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\felmeres.mp3",
    ["holvoltholnem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\holvoltholnem.mp3",
    ["hullanak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\hullanak.mp3",
    ["jarkalnaittmindig"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\jarkalnaittmindig.mp3",
    ["ketharomperc"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\ketharomperc.mp3",
    ["kilatta"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\kilatta.mp3",
    ["lattad"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\lattad.mp3",
    ["magyargardak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\magyargardak.mp3",
    ["megjelent"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\megjelent.mp3",
    ["megyekvarjal"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\megyekvarjal.mp3",
    ["nagyongyors"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\nagyongyors.mp3",
    ["nemlattam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\nemlattam.mp3",
    ["nemveszettel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\nemveszettel.mp3",
    ["rosszvege"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\rosszvege.mp3",
    ["telefonnelkul"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\telefonnelkul.mp3",
    ["telefonosszekottetes"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\telefonosszekottetes.mp3",
    ["teszemfel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\teszemfel.mp3",
    ["urazegbol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\urazegbol.mp3",
    ["xaktat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Fantom\\xaktat.mp3",
    ["betboz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\betboz.mp3",
    ["fobeloni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\fobeloni.mp3",
    ["kohazba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\kohazba.mp3",
    ["namitmondtal"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\namitmondtal.mp3",
    ["nehazudja"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\nehazudja.mp3",
    ["nemmondtal"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\nemmondtal.mp3",
    ["nemmondtam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\nemmondtam.mp3",
    ["rolammit"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\rolammit.mp3",
    ["szokesbevolt"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\szokesbevolt.mp3",
    ["vankulonbseg"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\vankulonbseg.mp3",
    ["vecesjoska"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\vecesjoska.mp3",
    ["veszett"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\veszett.mp3",
    ["zabalni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Gabi\\zabalni.mp3",
    ["alljunk_mar_meg"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\alljunk_mar_meg.mp3",
    ["beszarok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\beszarok.mp3",
    ["bohockodni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\bohockodni.mp3",
    ["buntetes"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\buntetes.mp3",
    ["csokifasszal"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\csokifasszal.mp3",
    ["el_lehet_jatszani"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\el_lehet_jatszani.mp3",
    ["faszt_jatszok_en"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\faszt_jatszok_en.mp3",
    ["fol_vagyok_haborodva"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\fol_vagyok_haborodva.mp3",
    ["haza_megyek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\haza_megyek.mp3",
    ["haza_mentem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\haza_mentem.mp3",
    ["hihi_hehe"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\hihi_hehe.mp3",
    ["hol_elunk"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\hol_elunk.mp3",
    ["kikerem_magamnak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\kikerem_magamnak.mp3",
    ["kozbe_szolni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\kozbe_szolni.mp3",
    ["maradjak_e"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\maradjak_e.mp3",
    ["megmutatta"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\megmutatta.mp3",
    ["musoron_kivul"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\musoron_kivul.mp3",
    ["nem_jatszom"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\nem_jatszom.mp3",
    ["nincs_csokifasz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\nincs_csokifasz.mp3",
    ["nincs_utomunka"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\nincs_utomunka.mp3",
    ["normalis_ember"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\normalis_ember.mp3",
    ["teteje_mindennek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\teteje_mindennek.mp3",
    ["tokom_tele_van"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\tokom_tele_van.mp3",
    ["van_televizio"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Havas\\van_televizio.mp3",
    ["ciganykolcson"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\ciganykolcson.mp3",
    ["hetfon11"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\hetfon11.mp3",
    ["hivatalba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\hivatalba.mp3",
    ["intezkednikell"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\intezkednikell.mp3",
    ["kiscsaladom"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\kiscsaladom.mp3",
    ["kizartdolog"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\kizartdolog.mp3",
    ["papaitanacs"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\papaitanacs.mp3",
    ["polgarmesternel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\polgarmesternel.mp3",
    ["polgarurhoz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\polgarurhoz.mp3",
    ["segitsegert"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\segitsegert.mp3",
    ["szocpolitikat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\szocpolitikat.mp3",
    ["tajekoztatast"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Hivatal\\tajekoztatast.mp3",
    ["baszomakurvaanyad"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\baszomakurvaanyad.mp3",
    ["baszomaszadat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\baszomaszadat.mp3",
    ["gyerebe"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\gyerebe.mp3",
    ["hekocsog"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\hekocsog.mp3",
    ["jaj"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\jaj.mp3",
    ["koldusvagy"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\koldusvagy.mp3",
    ["meghalsz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\meghalsz.mp3",
    ["oregfasz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\oregfasz.mp3",
    ["szazkurvaja"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\szazkurvaja.mp3",
    ["szetteplek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\szetteplek.mp3",
    ["verjeaszadba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Marika\\verjeaszadba.mp3",
    ["aludhatok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\aludhatok.mp3",
    ["avantgard"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\avantgard.mp3",
    ["boldogkaracsonyt"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\boldogkaracsonyt.mp3",
    ["egyszerkatona"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\egyszerkatona.mp3",
    ["elek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\elek.mp3",
    ["errefelenemoltem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\errefelenemoltem.mp3",
    ["fogadtam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\fogadtam.mp3",
    ["gyoztunk"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\gyoztunk.mp3",
    ["hellorofik"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\hellorofik.mp3",
    ["ilyenidoket"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\ilyenidoket.mp3",
    ["joetvagyat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\joetvagyat.mp3",
    ["kossuth"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\kossuth.mp3",
    ["magyar"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\magyar.mp3",
    ["masferfiakszoknyaja"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\masferfiakszoknyaja.mp3",
    ["megtudnek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\megtudnek.mp3",
    ["mezitlabas"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\mezitlabas.mp3",
    ["nemertettem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\nemertettem.mp3",
    ["orulokhogylattalak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\orulokhogylattalak.mp3",
    ["potvizsgara"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\potvizsgara.mp3",
    ["question"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\question.mp3",
    ["sajnalhatja"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\sajnalhatja.mp3",
    ["streetfighter"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\streetfighter.mp3",
    ["szexista"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\szexista.mp3",
    ["szoktamerregondolni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\szoktamerregondolni.mp3",
    ["templombol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\templombol.mp3",
    ["vereb"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Orban\\vereb.mp3",
    ["elturatni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Patkany\\elturatni.mp3",
    ["jobbanfelek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Patkany\\jobbanfelek.mp3",
    ["kiparancsol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Patkany\\kiparancsol.mp3",
    ["kiszolbele"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Patkany\\kiszolbele.mp3",
    ["megcsikart"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Patkany\\megcsikart.mp3",
    ["megharapott"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Patkany\\megharapott.mp3",
    ["namiertne"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Patkany\\namiertne.mp3",
    ["nincsottahelye"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Patkany\\nincsottahelye.mp3",
    ["azenyem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\azenyem.mp3",
    ["bekapod"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\bekapod.mp3",
    ["csecs"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\csecs.mp3",
    ["debroi"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\debroi.mp3",
    ["egycigit"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\egycigit.mp3",
    ["ezalenyeg"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\ezalenyeg.mp3",
    ["hulyegyerek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\hulyegyerek.mp3",
    ["lovattortem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\lovattortem.mp3",
    ["menjmar"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\menjmar.mp3",
    ["nemtart"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\nemtart.mp3",
    ["nyalogassa"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\nyalogassa.mp3",
    ["nyalogatom"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\nyalogatom.mp3",
    ["racuppanok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\racuppanok.mp3",
    ["szopjalegyet"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\szopjalegyet.mp3",
    ["tartabor"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Pepsi\\tartabor.mp3",
    ["aherbalazfu"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\aherbalazfu.mp3",
    ["amitmondottazjo"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\amitmondottazjo.mp3",
    ["bedrogoznak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\bedrogoznak.mp3",
    ["bedrogozva"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\bedrogozva.mp3",
    ["belovomis"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\belovomis.mp3",
    ["benyomoknekiolyat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\benyomoknekiolyat.mp3",
    ["bevagyokallva"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\bevagyokallva.mp3",
    ["bevanallva"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\bevanallva.mp3",
    ["bordokocsija"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\bordokocsija.mp3",
    ["csakbeszelgetunk"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\csakbeszelgetunk.mp3",
    ["csiga"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\csiga.mp3",
    ["dragamostnagyon"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\dragamostnagyon.mp3",
    ["drogoskocsog"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\drogoskocsog.mp3",
    ["elveszi"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\elveszi.mp3",
    ["flugosnyomozo"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\flugosnyomozo.mp3",
    ["forgasdki"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\forgasdki.mp3",
    ["fuvezzunk"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\fuvezzunk.mp3",
    ["gyerunk_drogozni-polg"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\gyerunk_drogozni.mp3",
    ["hajtsunk"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\hajtsunk.mp3",
    ["hakellkiutom"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\hakellkiutom.mp3",
    ["hogyvonak"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\hogyvonak.mp3",
    ["idee"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\idee.mp3",
    ["ilyenkedvem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\ilyenkedvem.mp3",
    ["ilyenpalitkiutok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\ilyenpalitkiutok.mp3",
    ["iskolaba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\iskolaba.mp3",
    ["kamera"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\kamera.mp3",
    ["ketgrammokat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\ketgrammokat.mp3",
    ["kikellkutatni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\kikellkutatni.mp3",
    ["kisherbal"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\kisherbal.mp3",
    ["kivagyokirva"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\kivagyokirva.mp3",
    ["kolatszoktam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\kolatszoktam.mp3",
    ["komlonegycsavo"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\komlonegycsavo.mp3",
    ["kristalyertadtamoda"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\kristalyertadtamoda.mp3",
    ["kristalyozni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\kristalyozni.mp3",
    ["loptamaztis"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\loptamaztis.mp3",
    ["margitkahoz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\margitkahoz.mp3",
    ["menjmarafaszomba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\menjmarafaszomba.mp3",
    ["mennekjobbrabalra"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\mennekjobbrabalra.mp3",
    ["merkeneottlenni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\merkeneottlenni.mp3",
    ["mikozukbele"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\mikozukbele.mp3",
    ["mindenjohet"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\mindenjohet.mp3",
    ["mindenvannala"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\mindenvannala.mp3",
    ["mitlat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\mitlat.mp3",
    ["mivanabba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\mivanabba.mp3",
    ["mostmivanabba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\mostmivanabba.mp3",
    ["mutassakfuvet"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\mutassakfuvet.mp3",
    ["nagyonnemtetszik"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\nagyonnemtetszik.mp3",
    ["nemszamit"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\nemszamit.mp3",
    ["nemvagyokkabitoszeres"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\nemvagyokkabitoszeres.mp3",
    ["nevelointezetbe"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\nevelointezetbe.mp3",
    ["nyilvanosnevemet"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\nyilvanosnevemet.mp3",
    ["ottadrogos"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\ottadrogos.mp3",
    ["rudikaszopol"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\rudikaszopol.mp3",
    ["sony"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\sony.mp3",
    ["szivjafel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\szivjafel.mp3",
    ["tekerjunkegyet"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\tekerjunkegyet.mp3",
    ["testverem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\testverem.mp3",
    ["vorosmarty"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\vorosmarty.mp3",
    ["zsebeben"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Polgarmester\\zsebeben.mp3",
    ["adjatok_bele"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\adjatok_bele.mp3",
    ["blackfasz"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\blackfasz.mp3",
    ["blokkolnam"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\blokkolnam.mp3",
    ["cica"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\cica.mp3",
    ["ember_meretu"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\ember_meretu.mp3",
    ["ez_a_szar"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\ez_a_szar.mp3",
    ["gyerunk_drogozni"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\gyerunk_drogozni.mp3",
    ["hanyas_vagy"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\hanyas_vagy.mp3",
    ["hitler"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\hitler.mp3",
    ["hogy_volt_merszed"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\hogy_volt_merszed.mp3",
    ["hol_vagy"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\hol_vagy.mp3",
    ["jarafaszom"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\jarafaszom.mp3",
    ["kiegtem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\kiegtem.mp3",
    ["kit_erdekel"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\kit_erdekel.mp3",
    ["kurva_anyadat"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\kurva_anyadat.mp3",
    ["kurva_anyatok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\kurva_anyatok.mp3",
    ["kurva_isten"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\kurva_isten.mp3",
    ["megbassza"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\megbassza.mp3",
    ["melyikkelkoll"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\melyikkelkoll.mp3",
    ["minden_no"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\minden_no.mp3",
    ["mostmar_ertem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\mostmar_ertem.mp3",
    ["neeem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\neeem.mp3",
    ["nem_buzi"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\nem_buzi.mp3",
    ["petikem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\petikem.mp3",
    ["pinaja_van"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\pinaja_van.mp3",
    ["sokkocsog"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\sokkocsog.mp3",
    ["szalljvelem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\szalljvelem.mp3",
    ["szarok_ratok"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\szarok_ratok.mp3",
    ["szerelmem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\szerelmem.mp3",
    ["szeretned"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\szeretned.mp3",
    ["szopj_le"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\szopj_le.mp3",
    ["tedd_a_szamba"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\tedd_a_szamba.mp3",
    ["tetszik_nekem"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\tetszik_nekem.mp3",
    ["te_kurva"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\te_kurva.mp3",
    ["te_nyomorek"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\te_nyomorek.mp3",
    ["vaah"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\vaah.mp3",
    ["very_big"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\very_big.mp3",
    ["veszelyes"] = "Interface\\AddOns\\hmc_reborn\\Sounds\\Uncategorized\\veszelyes.mp3",
}

-- Slash Command Handler
SLASH_HMC1 = "/hmc"
SlashCmdList["HMC"] = function(msg)
    local cmd = msg:lower():match("^%s*(.-)%s*$") -- Trim whitespace
    
    if cmd == "" or cmd == "ui" then
        addonTable.ShowUI()
    elseif HMC_Sounds[cmd] then
        local success = PlaySoundFile(HMC_Sounds[cmd], "Master")
        if not success then
             print("|cffff0000HMC Error:|r Could not play sound '" .. HMC_Sounds[cmd] .. "'")
        end
    else
        print("|cffff0000HMC:|r Sound '" .. cmd .. "' not found. Type /hmc for UI.")
    end
end

-- UI Construction
local f = CreateFrame("Frame", "HMC_MainFrame", UIParent, "BasicFrameTemplateWithInset")
f:SetSize(350, 450)
f:SetPoint("CENTER")
f:Hide()
f.TitleBg:SetHeight(30)
f.TitleBg:SetColorTexture(0.2, 0.2, 0.2, 1)
f.title = f:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
f.title:SetPoint("CENTER", f.TitleBg, "CENTER", 0, 0)
f.title:SetText("HMC Reborn Soundboard")

-- Close Button behavior is built-in to BasicFrameTemplateWithInset (the X button)

-- ScrollFrame
local scroll = CreateFrame("ScrollFrame", nil, f, "UIPanelScrollFrameTemplate")
scroll:SetPoint("TOPLEFT", 10, -40)
scroll:SetPoint("BOTTOMRIGHT", -30, 40) -- Room for bottom content if needed

local content = CreateFrame("Frame", nil, scroll)
content:SetSize(300, 1) -- Height updated dynamically
scroll:SetScrollChild(content)

-- Helper to create buttons
local function CreateSoundButton(parent, name, path, index)
    local btn = CreateFrame("Button", nil, parent, "UIPanelButtonTemplate")
    btn:SetSize(280, 24)
    btn:SetPoint("TOPLEFT", 5, -5 - (index-1)*26)
    btn:SetText(name)
    btn:SetNormalFontObject("GameFontNormalSmall")
    btn:SetHighlightFontObject("GameFontHighlightSmall")
    
    btn:SetScript("OnClick", function()
        PlaySoundFile(path, "Master")
    end)
    return btn
end

-- Populate List
local sortedNames = {}
for name in pairs(HMC_Sounds) do
    table.insert(sortedNames, name)
end
table.sort(sortedNames)

for i, name in ipairs(sortedNames) do
    CreateSoundButton(content, name, HMC_Sounds[name], i)
end

-- Adjust content height
content:SetHeight(#sortedNames * 26 + 10)

addonTable.ShowUI = function()
    f:Show()
end

-- Print loaded message
print("|cFF00FF00HMC Reborn|r loaded! Type /hmc to open.")
